# Generated by Django 4.1.3 on 2022-12-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_comment_comments_text_comments_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
